# Core

# Sets the default active profile
spring:
  profiles.active: development
  
app:
  admin:
    superadmin.role: SUPERADMIN
    token.secret: bGF4c3RhdHMgdG9rZW4gc2VjcmV0IGtleQ==

---

# DEVELOPMENT PROFILE CONFIGURATION

spring:
  profiles: development
  application:
    name: Laxstats Development
  
logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    laxstats: INFO
  file: C:/www/laxstats/log/laxstats.log
  
log4j:
  rootCategory: INFO, stdout
  
  appender:
    stdout: org.apache.log4j.ConsoleAppender
    stdout.layout: org.apache.log4j.PatternLayout
    stdout.layout.ConversionPattern: "%d{ABSOLUTE} %5p %t %c{2}:%L - %m%n"
    
  category:
    org.springframework.beans.factory: DEBUG
    org.springframework.boot.actuate.audit.listener: INFO
    laxstats: DEBUG
    
  logger:
    org.hibernate: INFO
    org.hibernate.type: ALL
    laxstats: DEBUG

# Server settings  
server:
  port: 8080
  address: localhost
  sessionTimeout: 30
  tomcat:
    uriEncoding: UTF-8

# Data Source
spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/laxstats_development
  username: root
  password: 

# JPA/Hibernate
spring.jpa:
  database: postgresql
  showSql: true
  hibernate:
    ddlAuto: update
    namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
  properties:
    validation:
      mode: none

# Spring Data 
spring.data:
  jpa:
    repositories:
      enabled: true

# MVC
spring.mvc:
  locale: en_US
  dateFormat: yyyy-MM-dd
  
# Thymeleaf
spring.thymeleaf:
  enabled: true
  cache: false

# Redis
spring.redis:
  host: localhost
  password:
  port: 6379

# Spring Mobile
spring.mobile:
  devicedelegatingviewresolver:
    enabled: true
    mobilePrefix:
    mobileSuffix: .mob

# Management server properties
management:
  security:
    enabled: true
    role: ADMIN
    sessions: stateless	

# Security properties
security:
  basic:
    enabled: false